# This rubocop config was copied from https://github.com/callmarx/dotfiles/blob/develop/.rubocop.yml.
# Based on https://rubystyle.guide and personal preferences. Be free to use e modify.

inherit_from:
  - .rubocop/base.yml
  - .rubocop/bundle.yml
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/naming.yml
  - .rubocop/security.yml
  - .rubocop/style.yml
  - .rubocop/performance.yml
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
